language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_TAG=google_apis

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t "android-25" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck --stacktrace

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-25
  licenses:
    - android-sdk-license-.+
    - '.+'

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"